/* Auto-generated by genmsg_cpp for file /home/nwadams/sb/10-11/ros-pkg/sb_msgs/msg/CarCommand.msg */
#ifndef SB_MSGS_MESSAGE_CARCOMMAND_H
#define SB_MSGS_MESSAGE_CARCOMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace sb_msgs
{
template <class ContainerAllocator>
struct CarCommand_ : public ros::Message
{
  typedef CarCommand_<ContainerAllocator> Type;

  CarCommand_()
  : throttle(0.0)
  , steering(0.0)
  {
  }

  CarCommand_(const ContainerAllocator& _alloc)
  : throttle(0.0)
  , steering(0.0)
  {
  }

  typedef double _throttle_type;
  double throttle;

  typedef double _steering_type;
  double steering;


private:
  static const char* __s_getDataType_() { return "sb_msgs/CarCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "39f463d271c2ca10c14182802c72c029"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "#Car command that arduinoDriver or furiousDriver can understand\n\
\n\
float64 throttle # throttle value -1 < x < 1\n\
float64 steering # steer value -1 < x < 1\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, throttle);
    ros::serialization::serialize(stream, steering);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, throttle);
    ros::serialization::deserialize(stream, steering);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(throttle);
    size += ros::serialization::serializationLength(steering);
    return size;
  }

  typedef boost::shared_ptr< ::sb_msgs::CarCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sb_msgs::CarCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct CarCommand
typedef  ::sb_msgs::CarCommand_<std::allocator<void> > CarCommand;

typedef boost::shared_ptr< ::sb_msgs::CarCommand> CarCommandPtr;
typedef boost::shared_ptr< ::sb_msgs::CarCommand const> CarCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sb_msgs::CarCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sb_msgs::CarCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sb_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::sb_msgs::CarCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "39f463d271c2ca10c14182802c72c029";
  }

  static const char* value(const  ::sb_msgs::CarCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x39f463d271c2ca10ULL;
  static const uint64_t static_value2 = 0xc14182802c72c029ULL;
};

template<class ContainerAllocator>
struct DataType< ::sb_msgs::CarCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sb_msgs/CarCommand";
  }

  static const char* value(const  ::sb_msgs::CarCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sb_msgs::CarCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Car command that arduinoDriver or furiousDriver can understand\n\
\n\
float64 throttle # throttle value -1 < x < 1\n\
float64 steering # steer value -1 < x < 1\n\
\n\
";
  }

  static const char* value(const  ::sb_msgs::CarCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::sb_msgs::CarCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sb_msgs::CarCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.throttle);
    stream.next(m.steering);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CarCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sb_msgs::CarCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sb_msgs::CarCommand_<ContainerAllocator> & v) 
  {
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SB_MSGS_MESSAGE_CARCOMMAND_H

