/* Auto-generated by genmsg_cpp for file /home/mark/snowbots/src/10-11/ros-pkg/sb_msgs/msg/TurretCommand.msg */
#ifndef SB_MSGS_MESSAGE_TURRETCOMMAND_H
#define SB_MSGS_MESSAGE_TURRETCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace sb_msgs
{
template <class ContainerAllocator>
struct TurretCommand_ {
  typedef TurretCommand_<ContainerAllocator> Type;

  TurretCommand_()
  : pan(0.0)
  , tilt(0.0)
  {
  }

  TurretCommand_(const ContainerAllocator& _alloc)
  : pan(0.0)
  , tilt(0.0)
  {
  }

  typedef double _pan_type;
  double pan;

  typedef double _tilt_type;
  double tilt;


private:
  static const char* __s_getDataType_() { return "sb_msgs/TurretCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "da61f3d6b381bd4af7a066f22fdfa441"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# A command for setting the position of a two-servo turret\n\
float64 pan  # between -1.0 and 1.0\n\
float64 tilt # between -1.0 and 1.0\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, pan);
    ros::serialization::serialize(stream, tilt);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, pan);
    ros::serialization::deserialize(stream, tilt);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(pan);
    size += ros::serialization::serializationLength(tilt);
    return size;
  }

  typedef boost::shared_ptr< ::sb_msgs::TurretCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sb_msgs::TurretCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TurretCommand
typedef  ::sb_msgs::TurretCommand_<std::allocator<void> > TurretCommand;

typedef boost::shared_ptr< ::sb_msgs::TurretCommand> TurretCommandPtr;
typedef boost::shared_ptr< ::sb_msgs::TurretCommand const> TurretCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sb_msgs::TurretCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sb_msgs::TurretCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sb_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sb_msgs::TurretCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sb_msgs::TurretCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sb_msgs::TurretCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "da61f3d6b381bd4af7a066f22fdfa441";
  }

  static const char* value(const  ::sb_msgs::TurretCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xda61f3d6b381bd4aULL;
  static const uint64_t static_value2 = 0xf7a066f22fdfa441ULL;
};

template<class ContainerAllocator>
struct DataType< ::sb_msgs::TurretCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sb_msgs/TurretCommand";
  }

  static const char* value(const  ::sb_msgs::TurretCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sb_msgs::TurretCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# A command for setting the position of a two-servo turret\n\
float64 pan  # between -1.0 and 1.0\n\
float64 tilt # between -1.0 and 1.0\n\
\n\
";
  }

  static const char* value(const  ::sb_msgs::TurretCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::sb_msgs::TurretCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sb_msgs::TurretCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pan);
    stream.next(m.tilt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TurretCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sb_msgs::TurretCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sb_msgs::TurretCommand_<ContainerAllocator> & v) 
  {
    s << indent << "pan: ";
    Printer<double>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<double>::stream(s, indent + "  ", v.tilt);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SB_MSGS_MESSAGE_TURRETCOMMAND_H

