"""autogenerated by genmsg_py from LidarNav.msg. Do not edit."""
import roslib.message
import struct


class LidarNav(roslib.message.Message):
  _md5sum = "f176eab4d8b8cab198d7795b194bf566"
  _type = "sb_msgs/LidarNav"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Message from LidarNav node to commander

float32 direction
float32 distance
int32 confidence #a percentage

"""
  __slots__ = ['direction','distance','confidence']
  _slot_types = ['float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       direction,distance,confidence
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(LidarNav, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.direction is None:
        self.direction = 0.
      if self.distance is None:
        self.distance = 0.
      if self.confidence is None:
        self.confidence = 0
    else:
      self.direction = 0.
      self.distance = 0.
      self.confidence = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2fi.pack(_x.direction, _x.distance, _x.confidence))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.direction, _x.distance, _x.confidence,) = _struct_2fi.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2fi.pack(_x.direction, _x.distance, _x.confidence))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.direction, _x.distance, _x.confidence,) = _struct_2fi.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2fi = struct.Struct("<2fi")
